# Generated by Django 5.0.7 on 2024-07-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the announcement.')),
                ('date', models.DateField(help_text='The date of the announcement.')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_no', models.IntegerField(help_text='Court number, must be a positive integer.')),
                ('start_time', models.DateTimeField(help_text='The start time of the reservation.')),
                ('duration', models.IntegerField(help_text='Duration of the reservation in hours.')),
                ('name', models.CharField(help_text='Name of the person making the reservation.', max_length=100)),
                ('phone', models.CharField(help_text='Phone number of the person making the reservation.', max_length=15)),
                ('email', models.EmailField(help_text='Email address of the person making the reservation.', max_length=254)),
                ('otp', models.CharField(help_text='One-time password for the reservation.', max_length=6)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
