# Generated by Django 5.0.7 on 2024-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badminton_court', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_status',
            field=models.BooleanField(default=False, help_text='Booking status, True if confirmed.'),
        ),
    ]
